name: terraforge_mobile
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/models/mineral_classifier_int8.tflite
    - assets/models/mineral_labels.txt
    - assets/models/geobotany_classifier_int8.tflite
    - assets/models/geobotany_labels.txt